### ISSUE TITLE
Periskop Server: Merge exceptions instead of swapping

### ISSUE THREAD

**Issue by jcreixell** [soundcloud/periskop#128]
Currently we swap one snapshot of services for another, resulting in an exact snapshot of errors from the last scrape.

This approach is simple but has the disadvantage of losing exception information after a deployment revert and posterior debugging, which is the first thing that happens on a bad deploy.

A more useful alternative would be to do a shallow merge of exceptions, so that older ones remain kept in memory. This does not solve the problem of losing exception information between Periskop deploys (which could be solved by introducing persistent storage), but it is an improvement over the current situation.

**Comment by genaforvena** [comment]
How merging should work example is here https://docs.google.com/document/d/110TAiUAtfKP2BIjD3Yg4dx7d6Hy3VX_eIbZ-gVhwDho/edit?ts=5f58c2d9
